### ISSUE TITLE
Errors when nothing needs fixing

### ISSUE THREAD

**Issue by cyberwombat** [Flet/standard-engine#129]
When I use standard such as this:

    cat test.js | standard --fix --stdin 1> result.js

And test.js contains valid StandardJS code:

    var foo = require('bar')

Then instead of emitting the file it returns an empty string and throws this error:
````
fs.js:2220
  fs.writeSync(this.fd, data, 0, data.length);
                                     ^
TypeError: Cannot read property 'length' of undefined
    at SyncWriteStream.write (fs.js:2220:38)
    at onResult (/usr/local/lib/node_modules/standard/node_modules/standard-engine/bin/cmd.js:101:22)
    at /usr/local/lib/node_modules/standard/node_modules/standard-engine/index.js:180:5
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
````

**Comment by feross** [comment]
You're right. This is indeed a bug. Fixed in PR #130

**Comment by feross** [comment]
Sounds good.

**Comment by feross** [comment]
Released as 5.1.1.

**Comment by cyberwombat** [comment]
Possible to push this to the standard repo release as well please?  Thank you

**Comment by Flet** [comment]
@cyberwombat It should be picked up automagically when reinstalling `standard` 

`standard` allows for semver patch level changes to `standard-engine`:
https://github.com/feross/standard/blob/master/package.json#L21

**Comment by cyberwombat** [comment]
it's... magic! :)
