### ISSUE TITLE
Tests are failing and possibly lintText method is not working

### ISSUE THREAD

**Issue by ricardofbarros** [Flet/standard-engine#4]
```shell
Error: Cannot find module 'eslint-config-standard'
Referenced from: /Users/rbarros/Desktop/github/standard-engine/node_modules/standard/rc/.eslintrc
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadConfig (/Users/rbarros/Desktop/github/standard-engine/node_modules/eslint/lib/config.js:91:34)
    at loadConfig (/Users/rbarros/Desktop/github/standard-engine/node_modules/eslint/lib/config.js:114:44)
    at new Config (/Users/rbarros/Desktop/github/standard-engine/node_modules/eslint/lib/config.js:329:34)
    at CLIEngine.executeOnFiles (/Users/rbarros/Desktop/github/standard-engine/node_modules/eslint/lib/cli-engine.js:318:28)
    at /Users/rbarros/Desktop/github/standard-engine/node_modules/standard/index.js:105:52
    at zalgoSafe (/Users/rbarros/Desktop/github/standard-engine/node_modules/dezalgo/dezalgo.js:20:10)
```

This could be easily fixed adding `eslint-config-standard` to dependencies.

**Comment by Flet** [comment]
ah yeah, adding `eslint-config-standard` to devDependencies should fix it!

**Comment by Flet** [comment]
Fixed in https://github.com/Flet/standard-engine/commit/5bd70fe43f073a0e7b122517a5595fea8e08b4b1
